"""add system_themes table for event designs

Revision ID: 3f3a14eaec2f
Revises: 2bf93cbb8b45
Create Date: 2026-09-23 21:37:23.957202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3a14eaec2f'
down_revision: Union[str, Sequence[str], None] = '2bf93cbb8b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
