"""system themes changed fixed

Revision ID: 765f24ee4dde
Revises: 3f3a14eaec2f
Create Date: 2026-09-24 18:57:44.979941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765f24ee4dde'
down_revision: Union[str, Sequence[str], None] = '3f3a14eaec2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
